// This file is generated by Firebase Studio.
import { initializeApp, getApps, getApp } from 'firebase/app';
import { getAuth } from 'firebase/auth';
import { getFirestore } from 'firebase/firestore';

const firebaseConfig = {
  projectId: 'howzue',
  appId: '1:86651209465:web:ed36b4042f08e7a7aa0428',
  storageBucket: 'howzue.firebasestorage.app',
  apiKey: 'AIzaSyDR-Tz2hr1QgC82z4c5bWLaYXaLYbo6Pww',
  authDomain: 'howzue.firebaseapp.com',
  measurementId: '',
  messagingSenderId: '86651209465',
};

// Initialize Firebase
const app = !getApps().length ? initializeApp(firebaseConfig) : getApp();
const auth = getAuth(app);
const db = getFirestore(app);

export { app, auth, db };
